export const TITLE = {
  LOGIN: "Đăng nhập",
  REGISTER: "Đăng ký",
  HOME: "Runner Inn | Trang chủ",
  PRODUCT_LIST: "Danh sách sản phẩm",
  PRODUCT_MEN: "Danh sách giày nam",
  PRODUCT_WOMEN: "Danh sách giày nữ",
  PRODUCT_KIDS: "Danh sách giày trẻ em",
  PRODUCT_DETAIL: "Thông tin sản phẩm",
  CART: "Giỏ hàng",
  BLOG: "Bài viết",
  CONTACT: "Liên hệ",
  ABOUT: "Giới thiệu",
  CHECKOUT: "Thanh toán",
  USER_PROFILE: "Quản lý tài khoản",
  USER_INFO: "Thông tin cá nhân",
  WISH_LIST: "Danh sách yêu thích",
  HISTORY_ORDER: "Lịch sử mua hàng",
  CHANGE_INFO: "Thay đổi thông tin",
};
